[package]
name = "ProjetoFinal"
version = "0.1.0"
edition = "2024"

[dependencies]
time = { version = "0.3.41", features = ["serde"] }
thiserror = "2.0.12"
rangemap = { version = "1.5.1", features = ["serde1"] }
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"